### ISSUE TITLE
Issues with latest proton clang

### ISSUE THREAD

**Issue by V3rB0se** [pri0818/falcon_kernel_realme_sm7125#1]
so i was trying to compile falcon but i couldn't compile it with latest proton clang. could be issues with latest proton update can you tell me what version of proton-clang you were using? 

## Log

`BUILDING Falcon-X KERNEL          

make[1]: Entering directory '/home/user/falcon/falcon_kernel_realme_sm7125-falcon/out'
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/basic/bin2c
  GEN     ./Makefile
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
\#
\# configuration written to .config
\#
make[1]: Leaving directory '/home/user/falcon/falcon_kernel_realme_sm7125-falcon/out'
make[1]: Entering directory '/home/user/falcon/falcon_kernel_realme_sm7125-falcon/out'
arch/arm64/Makefile:59: LSE atomics not supported by binutils
arch/arm64/Makefile:67: Detected assembler with broken .inst; disassembly will be unreliable
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
arch/arm64/Makefile:59: LSE atomics not supported by binutils
arch/arm64/Makefile:67: Detected assembler with broken .inst; disassembly will be unreliable
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using .. as source for kernel
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/dtc/dtc.o
  CC      scripts/mod/empty.o
  HOSTCC  scripts/selinux/genheaders/genheaders
/usr/bin/as: unrecognized option '-EL'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
make[3]: *** [../scripts/Makefile.build:365: scripts/mod/empty.o] Error 1
make[2]: *** [../scripts/Makefile.build:689: scripts/mod] Error 2
make[2]: *** Waiting for unfinished jobs....
  HOSTCC  scripts/dtc/flattree.o
  HOSTCC  scripts/dtc/fstree.o
  HOSTCC  scripts/selinux/mdp/mdp
  HOSTCC  scripts/dtc/data.o
  HOSTCC  scripts/dtc/livetree.o
  HOSTCC  scripts/dtc/treesource.o
  HOSTCC  scripts/dtc/srcpos.o
  HOSTCC  scripts/dtc/checks.o
  HOSTCC  scripts/dtc/util.o
  SHIPPED scripts/dtc/dtc-lexer.lex.c
  SHIPPED scripts/dtc/dtc-parser.tab.h
  SHIPPED scripts/dtc/dtc-parser.tab.c
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  HOSTLD  scripts/dtc/dtc
make[1]: *** [/home/user/falcon/falcon_kernel_realme_sm7125-falcon/Makefile:672: scripts] Error 2
make[1]: Leaving directory '/home/user/falcon/falcon_kernel_realme_sm7125-falcon/out'
make: *** [Makefile:146: sub-make] Error 2

`

**Comment by pri0818** [comment]
Hey....I am also having issues compiling with proton clang...but different and weird issue. Can you please link the proton clang you use ?

**Comment by V3rB0se** [comment]
> Hey....I am also having issues compiling with proton clang...but different and weird issue. Can you please link the proton clang you use ?

what issues? could you post the logs?

**Comment by pri0818** [comment]
Can you link the clang you are using ? BTW these are the logs

/home/priyanshusinghal0818/proton/bin/ld: /lib/x86_64-linux-gnu/libc.so.6: unknown type [0x13] section `.relr.dyn'
/home/priyanshusinghal0818/proton/bin/ld: skipping incompatible /lib/x86_64-linux-gnu/libc.so.6 when searching for /lib/x86_64-linux-gnu/libc.so.6
/home/priyanshusinghal0818/proton/bin/ld: cannot find /lib/x86_64-linux-gnu/libc.so.6
/home/priyanshusinghal0818/proton/bin/ld: /lib/x86_64-linux-gnu/libc.so.6: unknown type [0x13] section `.relr.dyn'
/home/priyanshusinghal0818/proton/bin/ld: skipping incompatible /lib/x86_64-linux-gnu/libc.so.6 when searching for /lib/x86_64-linux-gnu/libc.so.6
/home/priyanshusinghal0818/proton/bin/ld: /lib64/ld-linux-x86-64.so.2: unknown type [0x13] section `.relr.dyn'
/home/priyanshusinghal0818/proton/bin/ld: skipping incompatible /lib64/ld-linux-x86-64.so.2 when searching for /lib64/ld-linux-x86-64.so.2
/home/priyanshusinghal0818/proton/bin/ld: cannot find /lib64/ld-linux-x86-64.so.2
/home/priyanshusinghal0818/proton/bin/ld: /lib64/ld-linux-x86-64.so.2: unknown type [0x13] section `.relr.dyn'
/home/priyanshusinghal0818/proton/bin/ld: skipping incompatible /lib64/ld-linux-x86-64.so.2 when searching for /lib64/ld-linux-x86-64.so.2
collect2: error: ld returned 1 exit status

**Comment by V3rB0se** [comment]
i guess the binutils is not set up correctly or it isn't in your path btw I'm using [latest proton clang](https://github.com/kdrag0n/proton-clang/releases/tag/20210522) . while compiling it complains about a broken assembler maybe its my binutils because i have it installed for linux which is incompatible, I'll try purging ld and clang to see what's causing this.

**Comment by pri0818** [comment]
Try now...just clone this repo and run "bash falcon.sh"

**Comment by V3rB0se** [comment]
```
/home/user/proton-16/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/user/proton-16/bin/clang)
/home/user/proton-16/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/user/proton-16/bin/clang)
/home/user/proton-16/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/user/proton-16/bin/clang)
```

after pulling the latest changes and compiling the kernel again.

**Comment by pri0818** [comment]
> ```
> /home/user/proton-16/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/user/proton-16/bin/clang)
> /home/user/proton-16/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/user/proton-16/bin/clang)
> /home/user/proton-16/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/user/proton-16/bin/clang)
> ```
> 
> after pulling the latest changes and compiling the kernel again.

Works fine on Ubuntu 22.04 on gcp

**Comment by V3rB0se** [comment]
what do you mean by neutron in the script ?

**Comment by pri0818** [comment]
@priiii08 on telegram
